### ISSUE TITLE
Deploy Seaport Module for use with NFTEarth Exchange

### ISSUE THREAD

**Issue by westonnelson** [NFTEarth/nftearth-exchangev1#7]
###  NFTEarth Contracts and Information:

Conduit    address    0xFA29f9A402157672C2F608d193526A00C6B429Af
Channel    address    0x0f9b80fc3c8b9123D0aEf43Df58ebDBC034A8901
isOpen     bool       true
Conduit Controller    0x3E173b825ADEeF9661920B91A8d50B075Ad51bA5

### Seaport Module deployed on Optimism Mainnet currently reflects OpenSea's marketplace only at this contract address 0x00000000006c3852cbEf3e08E8dF289169EdE581:

ISeaport public constant EXCHANGE =
        ISeaport(0x00000000006c3852cbEf3e08E8dF289169EdE581);
        
function acceptERC20Listings(
        ISeaport.AdvancedOrder[] calldata orders,
        ERC20ListingParams calldata params,
        Fee[] calldata fees
    )
        external
        nonReentrant
        refundERC20Leftover(params.refundTo, params.token)
        chargeERC20Fees(fees, params.token, params.amount)
    {
        // Approve the exchange if needed
        _approveERC20IfNeeded(params.token, address(EXCHANGE), params.amount);

**Comment by Karthik-Gupta** [comment]
We have decided to go with our own router to be injected to SeaportModule. So here are the contracts deployed:
Router: 0x7c173d178B437287608d6105886DdC77CD40c089
SeaportModule: 0x2140Ea50bc3B6Ac3971F9e9Ea93A1442665670e4
